### ISSUE TITLE
Oauth2 v2 is incompatible and Oauth2 dependency is not bounded to <2.0.0

### ISSUE THREAD

**Issue by JCaporuscio** [bigcommerce/omniauth-bigcommerce#29]
Version 2.x of the oauth2 gem is incompatible - using it will result in "invalid client id" errors on attempting a BC store install.

Since the oauth2 version for this gem isn't limited to less than 2.0, any new installs or bundle updates will automatically pull in the absolute latest version causing project breakage.

While upgrading this gem to be compatible with oauth2 v2 would be a nice-to-have, at a minimum the oauth2 dependency should be limited to 1.x.

EDIT: Workaround is to explicitly include oauth2 in your gemfile with version 1.x

**Comment by hstrowd** [comment]
I was also able to work around this by explicitly adding `client_id` and `client_secret` to the set of `token_params` configured for this provider:

<img width="725" alt="Screenshot 2023-10-04 at 9 03 56 PM" src="https://github.com/bigcommerce/omniauth-bigcommerce/assets/420039/378b1a59-9b00-4b17-8e6f-7ead2b78cac3">

This works because the OAuth builder includes any `token_params` content within the set passed into the QAuth2 gem ([source](https://github.com/omniauth/omniauth-oauth2/blob/3e7ee11c84153e6f0c19d38a5e63cda550f6925c/lib/omniauth/strategies/oauth2.rb#L126C84-L126C96)), which then results in these being incorporated into the request body sent to the BigCommerce OAuth token creation endpoint ([source](https://gitlab.com/oauth-xx/oauth2/-/blob/37703150fc0970369400e0cd567da4ff408f1537/lib/oauth2/strategy/auth_code.rb#L30)).

**Comment by j05h** [comment]
@JCaporuscio, @hstrowd I'll get new release out which ensures we don't upgrade path oauth2 2.0.
